### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by SahilGera** [muggn/GY80#2]
// Copied error message
Arduino: 1.6.4 (Mac OS X), TD: 1.24, Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

/Users/sahil/Downloads/Arduino.app/Contents/Java/libraries/GY80-master/GY80.cpp: In constructor 'GY80::GY80()':
/Users/sahil/Downloads/Arduino.app/Contents/Java/libraries/GY80-master/GY80.cpp:9:5: error: 'g_scale_z' was not declared in this scope
     g_scale_z = 1;
     ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by T0T4R4** [comment]
Hi @SahilGera , just remove that line, that variable is not used. I'm using this lib for my project and will verify if the values displayed are consistent with other specific libraries for each sensor. Apart from the Magnetometer which shows only zeroes, the others seems allright for now.

**Comment by T0T4R4** [comment]
There is another warning :
`/GY80.cpp: In member function 'uint8_t* GY80::read(uint8_t, uint8_t, uint8_t)':
/GY80.cpp:413:10: warning: address of local variable 'buffer' returned [-Wreturn-local-addr]
  uint8_t buffer[length];`

And the solution suggested is to explicitely define the array, but not sure if this is a real issue or not. Seems to be working with the warning...
